# Generated by ./nix/gen-packages.sh
{ mkDerivation, aeson, amazonka, amazonka-core, amazonka-s3, base
, byteable, bytestring, Cabal, classy-prelude-conduit, conduit
, conduit-extra, containers, cryptonite, cryptonite-conduit
, directory, enclosed-exceptions, filepath, hit, hourglass
, http-client, http-client-tls, http-conduit, http-types, lens, lib
, memory, optparse-applicative, pretty, process, resourcet
, system-filepath, tar, temporary, text, utf8-string, yaml, zlib
}:
mkDerivation {
  pname = "all-cabal-tool";
  version = "0.1.1.0";
  src = ../../.;
  isLibrary = true;
  isExecutable = true;
  libraryHaskellDepends = [
    aeson base byteable bytestring Cabal classy-prelude-conduit conduit
    conduit-extra containers cryptonite cryptonite-conduit directory
    enclosed-exceptions filepath hit hourglass http-client
    http-client-tls http-conduit http-types memory pretty process
    resourcet system-filepath tar text utf8-string yaml zlib
  ];
  executableHaskellDepends = [
    aeson amazonka amazonka-core amazonka-s3 base bytestring
    classy-prelude-conduit conduit-extra directory http-client
    http-conduit http-types lens optparse-applicative temporary zlib
  ];
  homepage = "https://github.com/commercialhaskell/all-cabal-tool#readme";
  description = "Update the various all-cabal-* repos";
  license = lib.licenses.mit;
  mainProgram = "all-cabal-tool";
}
