# Generated by /nix/store/rz45l4mirazgpxsvmmy6kg67w4lbnx4b-gen-packages/bin/gen-packages
{ mkDerivation, amazonka-core, amazonka-test, base, bytestring
, case-insensitive, fetchgit, lib, tasty, tasty-hunit, text, time
, unordered-containers
}:
mkDerivation {
  pname = "amazonka-sts";
  version = "2.0";
  src = fetchgit {
    url = "https://github.com/brendanhay/amazonka";
    sha256 = "034d9rni0n95qmbc6fr13b7kbrs5s9s5qarg7znwx068gwf6293h";
    rev = "a7d699be1076e2aad05a1930ca3937ffea954ad8";
    fetchSubmodules = true;
  };
  postUnpack = "sourceRoot+=/lib/services/amazonka-sts; echo source root reset to $sourceRoot";
  libraryHaskellDepends = [ amazonka-core base ];
  testHaskellDepends = [
    amazonka-core amazonka-test base bytestring case-insensitive tasty
    tasty-hunit text time unordered-containers
  ];
  homepage = "https://github.com/brendanhay/amazonka";
  description = "Amazon Security Token Service SDK";
  license = lib.licensesSpdx."MPL-2.0";
}
