# Generated by update-deps
{ mkDerivation, aeson, amazonka-core, amazonka-sso, amazonka-sts
, base, bytestring, conduit, directory, exceptions, fetchgit
, http-client, http-conduit, http-types, ini, lib, resourcet, retry
, tasty, tasty-hunit, text, time, transformers
, unordered-containers, uuid
}:
mkDerivation {
  pname = "amazonka";
  version = "2.0";
  src = fetchgit {
    url = "https://github.com/brendanhay/amazonka";
    sha256 = "034d9rni0n95qmbc6fr13b7kbrs5s9s5qarg7znwx068gwf6293h";
    rev = "a7d699be1076e2aad05a1930ca3937ffea954ad8";
    fetchSubmodules = true;
  };
  postUnpack = "sourceRoot+=/lib/amazonka; echo source root reset to $sourceRoot";
  libraryHaskellDepends = [
    aeson amazonka-core amazonka-sso amazonka-sts base bytestring
    conduit directory exceptions http-client http-conduit http-types
    ini resourcet retry text time transformers unordered-containers
    uuid
  ];
  testHaskellDepends = [
    amazonka-core base http-client http-types tasty tasty-hunit time
  ];
  homepage = "https://github.com/brendanhay/amazonka";
  description = "Comprehensive Amazon Web Services SDK";
  license = lib.licensesSpdx."MPL-2.0";
}
