# Generated by /nix/store/133dapda5dm6ac69z3gpcrblisas65c2-gen-packages/bin/gen-packages
{ mkDerivation, array, base, bytestring, Cabal-syntax, containers
, deepseq, directory, filepath, lib, mtl, parsec, pretty, process
, time, transformers, unix
}:
mkDerivation {
  pname = "Cabal";
  version = "3.14.2.0";
  sha256 = "a58ca2b17c250472ed4dac0ec0aa2c65173701cbfdfecca104713f73b4429432";
  revision = "2";
  editedCabalFile = "0lwpdxz88115scx1zdfizy7dbva13zamwn5jx2ijkh773c4s622n";
  setupHaskellDepends = [ mtl parsec ];
  libraryHaskellDepends = [
    array base bytestring Cabal-syntax containers deepseq directory
    filepath mtl parsec pretty process time transformers unix
  ];
  doCheck = false;
  homepage = "http://www.haskell.org/cabal/";
  description = "A framework for packaging Haskell software";
  license = lib.licensesSpdx."BSD-3-Clause";
}
