# Generated by /nix/store/cpg9bv8brcvihpw3qsgawqvydpdklbw8-gen-packages/bin/gen-packages
{ mkDerivation, attoparsec, base, byteable, bytedump, bytestring
, containers, cryptohash, fetchgit, hourglass, lib, mtl, parsec
, patience, random, system-fileio, system-filepath, tasty
, tasty-quickcheck, unix-compat, utf8-string, vector, zlib
, zlib-bindings
}:
mkDerivation {
  pname = "hit";
  version = "0.6.3";
  src = fetchgit {
    url = "https://github.com/commercialhaskell/hit";
    sha256 = "182dzbjflq3gb9bv0h3fq504mq6y02xjfj1gjnqsncykf25h0din";
    rev = "1546b0c2a2f56e28b9ed5a1c5bf1a10adcad8b6c";
    fetchSubmodules = true;
  };
  isLibrary = true;
  isExecutable = true;
  enableSeparateDataOutput = true;
  libraryHaskellDepends = [
    attoparsec base byteable bytestring containers cryptohash hourglass
    mtl parsec patience random system-fileio system-filepath
    unix-compat utf8-string vector zlib zlib-bindings
  ];
  testHaskellDepends = [
    base bytedump bytestring hourglass tasty tasty-quickcheck
  ];
  homepage = "https://github.com/vincenthz/hit";
  description = "Git operations in haskell";
  license = lib.licenses.bsd3;
}
