# Generated by ./nix/gen-packages.sh
{ mkDerivation, base, containers, lib }:
mkDerivation {
  pname = "patience";
  version = "0.3";
  sha256 = "715cd08c99c0417462cee383c437c2b4384b6abbc87999fd092c8cf8e8192bc4";
  revision = "1";
  editedCabalFile = "0vldslyv381bmiw9f22wv46jmdcnxcjz5b8xqh8n7h7zzc5qs6j9";
  libraryHaskellDepends = [ base containers ];
  homepage = "https://github.com/chessai/patience";
  description = "Patience diff and longest increasing subsequence";
  license = lib.licenses.bsd3;
}
