#!/usr/bin/env bash
#
# Update all dependencies in one go.
#
# Usage: nix run .#update-deps
#
# This script:
# 1. Updates nixpkgs flake input
# 2. Syncs stack.yaml snapshot with nixpkgs LTS version
# 3. Checks Hackage for new Cabal versions
# 4. Regenerates nix package definitions

set -Eeuo pipefail

# Retry a command with exponential backoff
retry() {
    local max_attempts=3
    local delay=2
    local attempt=1

    while (( attempt <= max_attempts )); do
        if "$@"; then
            return 0
        fi
        echo "Attempt $attempt/$max_attempts failed, retrying in ${delay}s..." >&2
        sleep "$delay"
        (( attempt++ ))
        (( delay *= 2 ))
    done

    echo "All $max_attempts attempts failed" >&2
    return 1
}

# Temp files for parallel job results
lts_result=$(mktemp)
cabal_result=$(mktemp)
trap 'rm -f "$lts_result" "$cabal_result"' EXIT

#
# Step 1: Update flake inputs
#
echo "=== Updating flake inputs ==="
nix flake update

#
# Step 2: Fetch LTS and Cabal info in parallel
#
echo ""
echo "=== Fetching LTS and Cabal versions (parallel) ==="

# Background job: Get LTS version from GitHub
(
    nixpkgs_date=$(jq -r '.nodes.nixpkgs.locked.lastModified' flake.lock)
    nixpkgs_date_iso=$(date -d "@$nixpkgs_date" -u +%Y-%m-%dT%H:%M:%SZ)

    search_result=$(retry gh api "search/commits" \
        -X GET \
        -f q="repo:NixOS/nixpkgs haskellPackages stackage LTS committer-date:<=$nixpkgs_date_iso" \
        -f sort="committer-date" \
        -f order="desc" \
        -f per_page=1 \
        --jq '.items[0].commit.message')

    if [[ -z "$search_result" || "$search_result" == "null" ]]; then
        echo "Error: Could not find LTS commit" >&2
        exit 1
    fi

    lts_version=$(echo "$search_result" | grep -oP 'LTS \K[0-9]+\.[0-9]+' | tail -1)
    if [[ -z "$lts_version" ]]; then
        echo "Error: Could not parse LTS version" >&2
        exit 1
    fi

    echo "$lts_version"
) > "$lts_result" &
lts_pid=$!

# Background job: Get latest Cabal versions from Hackage
(
    cabal_ver=$(retry curl -sH "Accept: application/json" \
        "https://hackage.haskell.org/package/Cabal/preferred" | jq -r '.["normal-version"][0]')
    cabal_syntax_ver=$(retry curl -sH "Accept: application/json" \
        "https://hackage.haskell.org/package/Cabal-syntax/preferred" | jq -r '.["normal-version"][0]')
    echo "$cabal_ver $cabal_syntax_ver"
) > "$cabal_result" &
cabal_pid=$!

# Wait for both
wait "$lts_pid" || { echo "LTS fetch failed"; exit 1; }
wait "$cabal_pid" || { echo "Cabal fetch failed"; exit 1; }

lts_version=$(cat "$lts_result")
read -r cabal_latest cabal_syntax_latest < "$cabal_result"

echo "LTS version: $lts_version"
echo "Cabal: $cabal_latest, Cabal-syntax: $cabal_syntax_latest"

#
# Step 3: Update stack.yaml
#
echo ""
echo "=== Updating stack.yaml ==="

current_snapshot=$(grep -oP '^snapshot: lts-\K[0-9]+\.[0-9]+' stack.yaml || echo "")
if [[ "$current_snapshot" != "$lts_version" ]]; then
    echo "Updating snapshot: lts-$current_snapshot -> lts-$lts_version"
    sed -i "s/^snapshot: lts-.*/snapshot: lts-$lts_version/" stack.yaml
else
    echo "Snapshot already at lts-$lts_version"
fi

cabal_current=$(grep -oP "^- Cabal-\\K[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+" stack.yaml || echo "")
if [[ "$cabal_current" != "$cabal_latest" ]]; then
    echo "Updating Cabal: $cabal_current -> $cabal_latest"
    sed -i "s/^- Cabal-${cabal_current}/- Cabal-${cabal_latest}/" stack.yaml
else
    echo "Cabal already at $cabal_latest"
fi

cabal_syntax_current=$(grep -oP "^- Cabal-syntax-\\K[0-9]+\\.[0-9]+\\.[0-9]+\\.[0-9]+" stack.yaml || echo "")
if [[ "$cabal_syntax_current" != "$cabal_syntax_latest" ]]; then
    echo "Updating Cabal-syntax: $cabal_syntax_current -> $cabal_syntax_latest"
    sed -i "s/^- Cabal-syntax-${cabal_syntax_current}/- Cabal-syntax-${cabal_syntax_latest}/" stack.yaml
else
    echo "Cabal-syntax already at $cabal_syntax_latest"
fi

#
# Step 4: Regenerate nix packages (parallel)
#
echo ""
echo "=== Regenerating nix packages (parallel) ==="

# Extract amazonka commit from stack.yaml
amazonka_commit=$(grep -A1 'github: brendanhay/amazonka' stack.yaml | grep 'commit:' | awk '{print $2}')
echo "amazonka commit: $amazonka_commit"

cd nix/packages

# Helper for generating a package
gen_pkg() {
    local name="$1"
    shift
    echo "# Generated by update-deps" > "${name}.nix.tmp"
    retry cabal2nix "$@" >> "${name}.nix.tmp"
    mv "${name}.nix.tmp" "${name}.nix"
    echo "  ${name}: done"
}

# Local package
gen_pkg all-cabal-tool ../.. &
pid1=$!

# GitHub packages
gen_pkg hit https://github.com/commercialhaskell/hit &
pid2=$!

# Hackage packages
gen_pkg patience cabal://patience &
pid3=$!

gen_pkg Cabal "cabal://Cabal-${cabal_latest}" &
pid4=$!

gen_pkg Cabal-syntax "cabal://Cabal-syntax-${cabal_syntax_latest}" &
pid5=$!

# Amazonka packages (all from same repo)
gen_pkg amazonka "https://github.com/brendanhay/amazonka" --revision "$amazonka_commit" --subpath lib/amazonka &
pid6=$!

gen_pkg amazonka-core "https://github.com/brendanhay/amazonka" --revision "$amazonka_commit" --subpath lib/amazonka-core &
pid7=$!

gen_pkg amazonka-s3 "https://github.com/brendanhay/amazonka" --revision "$amazonka_commit" --subpath lib/services/amazonka-s3 &
pid8=$!

gen_pkg amazonka-sso "https://github.com/brendanhay/amazonka" --revision "$amazonka_commit" --subpath lib/services/amazonka-sso &
pid9=$!

gen_pkg amazonka-sts "https://github.com/brendanhay/amazonka" --revision "$amazonka_commit" --subpath lib/services/amazonka-sts &
pid10=$!

# Wait for all
failed=0
for pid in $pid1 $pid2 $pid3 $pid4 $pid5 $pid6 $pid7 $pid8 $pid9 $pid10; do
    wait "$pid" || ((failed++))
done

cd ../..

if [[ $failed -gt 0 ]]; then
    echo "ERROR: $failed package(s) failed to generate"
    exit 1
fi

echo ""
echo "=== All done! ==="
